# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('existed', models.BooleanField()),
                ('last_found', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='You_TubeChannel',
            fields=[
                ('channelID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('channelName', models.CharField(max_length=100)),
                ('number_of_videos', models.IntegerField()),
                ('number_of_old_videos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='reference_to_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YT_model.You_TubeChannel'),
        ),
    ]
